### PR TITLE
K9 version

### LINKED ISSUE #10: EasyThreed K9 version
I have an EasyThreed K9 with ET4000+ board, but it has a few differences. Some perfipherals are missing and wifi board connector is used by the front panel buttons. Would you be interested in making another repo for K9 if I provide photos and pin/button mappings?

### PR DESCRIPTION
**Pull request by JohnTheCoolingFan**
This pull request adds compatibility for the K9 printer using ET4000+ board

Closes #10 

Also the PR discussion will serve to log the progress of exploration of the device.

### CODE REVIEW

**Comment by JohnTheCoolingFan** [comment]
@schmttc so I added tables explaining the button connection on wifi module port and EXP1 connector, it looks like they differ drastically from K7 if I understood the schematics right.

**Comment by JohnTheCoolingFan** [comment]
Also, here's a photo of the board compartment / printer base:

IMG_20231005_205354

**Review by schmttc — APPROVED** [review]

**Comment by JohnTheCoolingFan** [comment]
I've asked easythreed for a firmware source, they responded with a config file and a compiled firmware binary.

Config is in this gist: https://gist.github.com/JohnTheCoolingFan/39227f4ddd12a7c614d4e360d0473e6a

And the firmware is available through my webserver: https://jtcf.ru/EasyThreed-K9-factory-firmware.bin (Also uploaded to yandex.disk just in case: https://yadi.sk/d/pkLMmOElof_DlA)

**Comment by JohnTheCoolingFan** [comment]
So, from the config it is clear that teh MKS Robin Lite was used as a base. The config doesn't tell a lot about hardware configuration, though. Since the firmware file is available, decompilation might be a possibility, although it's something I've never done before.

Well, progress is progress.

**Comment by schmttc** [comment]
They seem to do that a lot.
Push them a bit, tell them you want to enable some additional firmware features including backlash compensation to fix non-round circles, and you need the firmware source code to make the changes.

**Comment by JohnTheCoolingFan** [comment]
I asked them for the source code explicitly, stating your reasoning for why I would need it. No reply yet but I will try to get a status update on that if they don't send it until the weekend.

On a side note: my K9 printer got a malfunction. Starting a print or trying to feed/retracts leads to freezing up after the nozzle heats up or just right away if trying to print. After soem troubleshooting it seems to be a software issue, which persists even after updating the firmware to the one they sent me. I, honestly, don't know what to do in here, but I'm open for discussion about it on discord or somewhere else, as this would be off-topic here.

**Comment by schmttc** [comment]
I was just thinking about this and remembered that all of the EasyThreed printers are all the same hardware in a different form factor; so you could try and flash my K7 firmware and it might all just work, except for the homing buttons.
If it doesn't work, you can just flash back,I've flashed plenty of bad firmwares and always been able to roll back.
Try this one https://github.com/schmttc/EasyThreeD-K7-STM32/blob/backlashfix/mksLite.bin

**Comment by JohnTheCoolingFan** [comment]
@schmttc Unfortunately, flashing teh file you linked didn't work. The printer didn't really respond to buttons and switches. I flashed back the firmware they gave me and it still behaves the same as before the K7 firmware flash.

**Comment by schmttc** [comment]
I don't know why they'd change the wiring, but anyway 

If you can map your pinout to the processor pins (eg. PA1 etc) using the schematic pdf, we should be able to get it going.
https://github.com/schmttc/EasyThreeD-K7-STM32/blob/Additional-Files/ET4000%2B.pdf

What is the functionality of the 4 homing buttons?

**Comment by schmttc** [comment]
@JohnTheCoolingFan  also, over here https://github.com/schmttc/EasyThreeD-K7-STM32/issues/2 I had a freeze issue within the first layer or two that I wasn't able to pin down, but it only happened when I use the latest bugfix code. Tom thought it might have been related to our board, as he wasn't able to reproduce. Does the print continue if you leave it a few minutes? And have you reached out to EasyThreed about it?
It might be worth starting a separate ticket back on the main Marlin repo.

**Comment by JohnTheCoolingFan** [comment]
I've tried leaving the printer for a long time after it freezes. It doesn't even start printing, just stops everything after heating up teh nozzle. I haven't reached to EasyThreed about it yet.

**Comment by schmttc** [comment]
> @schmttc Unfortunately, flashing teh file you linked didn't work. The printer didn't really respond to buttons and switches. I flashed back the firmware they gave me and it still behaves the same as before the K7 firmware flash.

I've mapped out the pins, and only the start button function (and levelling keys) should have been not working.
Can you please confirm if the LED on the start button; and the feed/retract filament switch, and the home button worked?
If these work, I can quickly fix up a firmware with backlash correction that will function except the levelling keys.

**Comment by schmttc** [comment]
Another thing to check on the freezing. 
Is the hotbed enabled in the config file; but you don't have a heated bed? If this happens, the printer will try to heat the bed, and then a safety will kick in after I think 10s if the temp doesn't rise, and the printer will hard stop.

**Comment by JohnTheCoolingFan** [comment]
@schmttc Can confirm that teh firmware you linked for K7 works with the feed/retract switch.

**Comment by JohnTheCoolingFan** [comment]
By the way, what do you think about teh front 4 leveling buttons? I find it weird that two buttosn are connected to ground and the other two are connected to 3v3.
Also, making this PR ready for review to at least merge the pin tracing I put into tables to your repo

**Comment by JohnTheCoolingFan** [comment]
Oh, right, I didn't expect the front 4 leveling buttons behavior.
They move the nozzle to one of 4 points. They are not directly at the corners but are a bit inset. And when pressing the 1 button, the homing sequence always executes again. The order is close left, close right, far right and far left.

**Comment by JohnTheCoolingFan** [comment]
One thing I noticed about the "new" K9 "stock" formware Easythreed support sent me: the travel speed when leveling (moving from one point to another) or getting to the right height before homing is very slow. Much slower than what it was from teh factory. The homing sequence's speed is the same.

**Comment by schmttc** [comment]
Glad it's working again.

1. I can't trace the 4 button board back to the processor pins from the schematic, so I don't know how to get them working yet.
2. The GND/3V3 on the 4 buttons isn't a problem, just a bit weird. 
3. I've attached a firmware with the current code, this should get the print button working (or if the wiring is reversed, it will try and print straight away, let me know) 
[mksLite.bin.txt](https://github.com/schmttc/EasyThreeD-K7-STM32/files/13462842/mksLite.bin.txt)

**Comment by JohnTheCoolingFan** [comment]
The 4 front levelling buttons are connected through a ribbon cable to a daughter board that is plugged into the slot for the MKS Wifi module. I've specified the numbers and the numbering order in the table I made, I can try and trace it to the processor if you can't.

**Comment by schmttc** [comment]
Yes if you can trace it to processor pins we can get them working.
The last page on the schematic has the pinout but it isn't in a logical order that I can make out to map through.

**Comment by JohnTheCoolingFan** [comment]
Alright, traced out and tested wit ha multimeter, these should be the mappings:

- Button 1 signal - IO1, goes to PC7 (pin 38)
- Button 2 signal - IO2, goes to PC11 (pin 52)
- Button 3 signal - WiFi TX, goes to USART2_TX, PA2 (pin 16)
- Button 4 signal - WiFi RX, goes to USART2_RX, PA3 (pin 17)

@schmttc Doesn't seem like any of the pins conflict, the uart pins are just not used as serial I guess.

**Comment by JohnTheCoolingFan** [comment]
Also, your schematics say that TXD0 and RXD0 go to the wifi module. From my testing, USART2_{T,R}X go there.

**Comment by schmttc** [comment]
Give this one a try, the levelling keys should work. If it tries to level as soon as you've turned it on I've got the high/low the wrong way.
[mksLite.bin.txt](https://github.com/schmttc/EasyThreeD-K7-STM32/files/13472549/mksLite.bin.txt)

**Comment by JohnTheCoolingFan** [comment]
@schmttc Just tried the firmware you linked. It doesn't work properly. The print button seems to work, but the printing routine doesn't. When homing by going to the max/min positions of teh axes, it gets stuck moving down (z axis). It reached the lowest position and was still trying to turn the motor for a significant amount of time before I powered it off.

The leveling buttons don't seem to take any effect at all.

**Comment by JohnTheCoolingFan** [comment]
Also tried the previous version from here: https://github.com/schmttc/EasyThreeD-K7-STM32/pull/11#issuecomment-1826190351

For some reason, the print button is not working and instead the levelling button 1 has its function. I think it was the same on the next version, I just didn't bother to investigate that time.

**Comment by JohnTheCoolingFan** [comment]
Oh, I see where the issue stems from. I'll re-check what pin the front print button goes to.

**Comment by JohnTheCoolingFan** [comment]
Alright, did some fixes based on info I found. I also researched the print button a bit more, got complete mapping for teh board. It has 4 pins, GND, LED+ (Connected to 3v3, VDDA), LED- (PD2), SW (PA10). SW is the print button, connects to GND. I already replaced that in the code in [57b9a3f](https://github.com/schmttc/EasyThreeD-K7-STM32/pull/11/commits/57b9a3fbb63922527b3e02303935f6e6b17d06b4).

**Comment by schmttc** [comment]
Thanks for updating the print pin.

For the homing Z issue, either the Z limit switch is plugged in to the wrong socket, or they've used a different pin.

To debug the limit switch and the levelling buttons, you can connect the printer to your computer using Repetier-Host or some other terminal program, and issue a "M43" command to get the button statuses. Then hold down the button and issue M43 again.
Then check to see which pin changed state.

**Comment by JohnTheCoolingFan** [comment]
K9 doesn't have any limit switches, so you shouldn't use them at all.

**Comment by schmttc** [comment]
It looks like the Z Home speed in my firmware is 240mm/min, and in the config file for K9 it's 600mm/min. With no Z stop that's 25s vs 10s to run down 100mm.
How long does it take to home Z with the out of box firmware?

**Comment by JohnTheCoolingFan** [comment]
It takes about 4-5 seconds to home for each axis, I measured 4.6 seconds by using my phone and starting/stopping it by hand.

**Comment by JohnTheCoolingFan** [comment]
Also, the stock homing for the table (Y) axis is to go farthest to the back (to the side of the motor), while yours homed it to the front, which I think is much better.

The K9 uses 3 identical axis assemblies which get clipped in and then screwed together, kind of a modular system.

**Comment by schmttc** [comment]
I've updated the print key and set Z to home at 600mm/min (same as out of box config). Let me know how the Z home speed compares. Binary attached.
[mksLite.bin.txt](https://github.com/schmttc/EasyThreeD-K7-STM32/files/13495684/mksLite.bin.txt)

**Comment by JohnTheCoolingFan** [comment]
The Z speed is ok, it finished the homing sequence, but it was stuck in teh bottom possition and trying to spin the motor for too long compared to the stock firmware. Would you like me to record how the homing sequence looks with the stock firmware and how yours looks?

**Comment by JohnTheCoolingFan** [comment]
And regarding the buttons - only the homing button works. The print button and levelling byttons do not work.

**Comment by schmttc** [comment]
> The Z speed is ok, it finished the homing sequence, but it was stuck in teh bottom possition and trying to spin the motor for too long compared to the stock firmware. Would you like me to record how the homing sequence looks with the stock firmware and how yours looks?

Yes, that would help to understand what it's doing.

> And regarding the buttons - only the homing button works. The print button and levelling buttons do not work.

Can you run a M43 check for the print and levelling buttons, they must be on different pins.

**Comment by JohnTheCoolingFan** [comment]
Here's a video of teh stock vs custom firmware: https://youtu.be/v2AZid0vtRQ

Also, I tried the M43 command over usb but it keeps telling  that `M43` is and unknown command. Other commands like G28 work fine.

**Comment by schmttc** [comment]
My bad, it wasn't enabled. Try this firmware for M43. I'll look into the homing behaviour later.
[mksLite.bin.txt](https://github.com/schmttc/EasyThreeD-K7-STM32/files/13499385/mksLite.bin.txt)

**Comment by JohnTheCoolingFan** [comment]
Ok, I seem to have ignored teh hit states for the levelling buttons when putting their configs together. Should be corrected now. Some button pins how up as unused/unknown, some show up with proper names. Some of thsie show the input value, some don't. BUTTON2 and BUTTON3 are bound to PA2 and PA3 but those are for BUTTON3 and BUTTON4 respectively. BUTTON1 doesn't react to the press (stays High, I guess because of incorrect hit states) and it doesn't show it's pin, PC7 is unused/unknown instead. Button 2 on PC11 reacts to the press but doesn't show the name as BUTTON2.

The output is a mess honestly. There may be something wrong with my screen config because it doesn't seem to handle newlines properly.

**Comment by JohnTheCoolingFan** [comment]
It looks like the firmware you sent doesn't use the button mapping I made and instead uses a previous version made by you.

**Comment by JohnTheCoolingFan** [comment]
Here's a gist with the output of M43: https://gist.github.com/JohnTheCoolingFan/f4719b093dd3143147b88eeb4b3eea19

**Comment by schmttc** [comment]
If you're using platformio you can install the "Auto Build Marlin" plugin which makes compiling the firmware really easy. Then you can run through various testing without having to wait for me :)
You'll just have to uncomment ```#define PINS_DEBUGGING``` in Configuration_adv.h

- "<unused/unknown>" means the pin isn't mapped to an alias by the firmware (this usually means it's not used, but not always)
- "Input  HIGH" means the pin is set as an input; and the current state is HIGH. If you hold down a button and run M43 this state should change

**Comment by JohnTheCoolingFan** [comment]
I am using platformio, but only command-line, I don't use visual studio code. But I'll try to figure out the building and flashing steps myself.

**Comment by schmttc** [comment]
For cli, from the root folder with the source code, I think it should be ```platformio run -e mks_robin_lite_maple```
And the binary should go to root\.pio\build\mks_robin_lite_maple\mksLite.bin

**Comment by JohnTheCoolingFan** [comment]
I accidentally pushed "Discard commits"... Thankfully I had a local version where I could also merge and push the commits back.

**Comment by JohnTheCoolingFan** [comment]
Currently, the levelling buttons 3 and 4 get triggered constantly is the trigger state is `HIGH`. I've checked to see what's going on and when the device is powered, the button pin has around 1.6V on it. Doesn't seem to actually be connected to any resistor and the button pin is set to input as floating by Marlin. When those buttons' hit states are set to `LOW`, they essentially become disabled and buttons 1 and 2 work without issues. The daughter board only has the 4 buttons and a connector, nothing else.

**Comment by schmttc** [comment]
Try adding this to the K9 block in pins_MKS_ROBIN_LITE.h to address the floating input pins
SET_INPUT_PULLDOWN(PA2);
SET_INPUT_PULLDOWN(PA3);

**Comment by JohnTheCoolingFan** [comment]
Yep, that worked. I'll now adjust the speeds, probably to those that easythreed support sent me.

**Comment by JohnTheCoolingFan** [comment]
Alright, turns out I incorrectly mapped the button pin. It's actually on PA11, the same as K7. Also added it to the pins debug list so I could debug it, I will leave it as I think it's useful.

I didn't manage to find the home feddrate adjustments in teh configuration but I think the current ones work well enough.

Will do a test print later!

**Comment by schmttc** [comment]
Thinking about the printer homing to a different corner, one of the axes may be inverted, which may be a problem.

**Comment by schmttc** [comment]
@JohnTheCoolingFan I hope you've been well, just checking in to see if you've had time to run that test print and need to make any tweaks before we merge.

**Comment by JohnTheCoolingFan** [comment]
Ah, I'm alright and I did try to do a test print, but I guess my setup without bed heating isn't good for petg as it curls up and has issues sticking to the build plate (Even though I'm using a PEA bed). Using a bare plastic bed with stick glue yielded better results previously...

As for the firmware, clearly the Y axis is inverted, that can be seen even with the first layer of benchy.

**Comment by JohnTheCoolingFan** [comment]
Oh, and sometimes when powering on, it may go to one of the levelling corners.

**Comment by schmttc** [comment]
- Y axis issue: in Configuration.h change ```#define INVERT_Y_DIR false``` to true
- Is the power on levelling corner move always the same corner, or does it vary? I wonder if this is to do with setting the input pulldown, maybe we need to do it in say the pins file that gets processed earlier.
- I've only printed PLA/PLA+ and TPU with my K7, but I find masking/painters tape works very well for an unheated bed with these filaments

**Comment by JohnTheCoolingFan** [comment]
I don't think a test print is really that necessary for testing the firmware. Tried printing a benchy with PLA, but it just detached from the build plate at some point. I have ordered a hotbed, should arrive soon, would be a nice upgrade. I will not submit hotbed changed to the repo as that's not in the default K9 configuration.

For the corner, the input pullup/pulldown can only be set at runtime, not in defines. So I put these to Easytheed UI init function.

**Comment by schmttc** [comment]
No worries. I'll merge this PR to baseline all the work so far, and we can tweak it later if needed.

**Review by schmttc — APPROVED** [review]

**Comment by JohnTheCoolingFan** [comment]
The 3d printer always goes to corner that corresponds to button 4. I'll try some tweaks I did since last firmware update and see how it goes. Also will try to re-level my bed and print again, maybe it won't detach so easily.

**Comment by JohnTheCoolingFan** [comment]
@schmttc Hey, I just installed hotbed on my printer and I'm trying to edit the configuration so it would use it. Where can I enable it, if I even need to change something?

**Comment by schmttc** [comment]
TEMP_SENSOR_BED in configuration.h is already enabled, you should be able to set the bed temp in your slicer and it will work.

**Pull request merged**
